puts "The Students of Villains Academy"
puts "===================="
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Norman Bates"
puts "Michael Corleone"
puts "Patrick Bateman"
puts "Tyler Durden"
puts "Freddy Kreuger"
puts "The Joker"
